USE [master]
GO

/****** Object:  Database [Pìzzaria]    Script Date: 26/03/2018 12:22:43 ******/
CREATE DATABASE [Pìzzaria] ON  PRIMARY 
( NAME = N'Pìzzaria', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\Pìzzaria_Dados' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Pìzzaria_log', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\Pizzaria_log' , SIZE = 5120KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Pìzzaria] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Pìzzaria].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Pìzzaria] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Pìzzaria] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Pìzzaria] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Pìzzaria] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Pìzzaria] SET ARITHABORT OFF 
GO

ALTER DATABASE [Pìzzaria] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Pìzzaria] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Pìzzaria] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Pìzzaria] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Pìzzaria] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Pìzzaria] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Pìzzaria] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Pìzzaria] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Pìzzaria] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Pìzzaria] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Pìzzaria] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Pìzzaria] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Pìzzaria] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Pìzzaria] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Pìzzaria] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Pìzzaria] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Pìzzaria] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Pìzzaria] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Pìzzaria] SET  MULTI_USER 
GO

ALTER DATABASE [Pìzzaria] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Pìzzaria] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Pìzzaria] SET  READ_WRITE 
GO


